variables:
  AUDIT_AWS_S3_ALERT_LIST:
    description: "Which alerts would you like to check for? (Default is all S3 alerts)"
    required: true
    type: array
    default:
      - s3-allusers-write
      - s3-allusers-write-acp
      - s3-allusers-read
      - s3-authenticatedusers-write
      - s3-authenticatedusers-write-acp
      - s3-authenticatedusers-read
      - s3-logging-disabled
      - s3-world-open-policy-delete
      - s3-world-open-policy-get
      - s3-world-open-policy-list
      - s3-world-open-policy-put
      - s3-world-open-policy-all
      - s3-only-ip-based-policy
  AUDIT_AWS_S3_ALERT_RECIPIENT:
    description: "Enter the email address(es) that will receive notifications. If more than one, separate each with a comma."
    required: true
    type: string
    default:
  AUDIT_AWS_S3_ALLOW_EMPTY:
    description: "Would you like to receive empty reports? Options - true / false. Default is false."
    required: true
    type: string
    default: true
  AUDIT_AWS_S3_SEND_ON:
    description: "Send reports always or only when there is a change? Options - always / change. Default is change."
    required: true
    type: string
    default: "change"
  AUDIT_AWS_S3_REGIONS:
    description: "List of AWS regions to check. Default is us-east-1,us-west-1,us-west-2."
    required: true
    type: array
    default:
        - us-east-1
        - us-east-2
        - us-west-1
        - us-west-2
        - eu-west-1
  AUDIT_AWS_S3_FULL_JSON_REPORT:
    description: "Would you like to send the full JSON report? Options - notify / nothing. Default is notify."
    required: true
    type: string
    default: "nothing"
  AUDIT_AWS_S3_ROLLUP_REPORT:
    description: "Would you like to send a Summary ELB report? Options - notify / nothing. Default is no / nothing."
    required: true
    type: string
    default: "nothing"
  AUDIT_AWS_S3_OWNERS_HTML_REPORT:
    description: notify or nothing
    required: true
    type: string
    default: "notify"
  AUDIT_AWS_S3_ALERT_RECIPIENT_2:
    description: "Enter the email address(es) that will receive notifications for objects with no owner tag (Optional, only if owner tag is enabled)."
    required: false
    type: string
    default:
  AUDIT_AWS_S3_OWNER_TAG:
    description: "Enter an AWS tag whose value is an email address of owner of the ELB object. (Optional)"
    required: false
    type: string
    default: "NOT_A_TAG"
